version: "3.3"
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - "constraint:node==qserver"
  clock:
    image: rqure/clock:v2.0.2
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
