version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - "constraint:node==qserver"
  clock:
    image: rqure/clock:v2.0.12
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
  exchange:
    image: rqure/exchange:v2.0.5
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
  audio-player:
    image: rqure/audio-player:v1.0.8
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
  prayer:
    image: rqure/prayer:v2.0.2
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
  dmm:
    image: rqure/dmm:v1.0.0
    restart: unless-stopped
    privileged: true
    deploy:
      mode: global
  mosquitto:
    image: rqure/mosquitto:v1.0.0
    ports:
      - 1883:1883
      - 9001:9001
    deploy:
      mode: replicated
      replicas: 1
  zigbee2mqtt:
    image: rqure/zigbee2mqtt:v1.0.0
    restart: unless-stopped
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
networks:
  default:
    attachable: true
