version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
  clock:
    image: rqure/clock:v2.0.13
    deploy:
      mode: replicated
      replicas: 1
  exchange:
    image: rqure/exchange:v2.0.7
    deploy:
      mode: replicated
      replicas: 1
  audio-player:
    image: rqure/audio-player:v1.0.10
    deploy:
      mode: replicated
      replicas: 1
  prayer:
    image: rqure/prayer:v2.0.3
    deploy:
      mode: replicated
      replicas: 1
  dmm:
    image: rqure/dmm:v1.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
  mosquitto:
    image: rqure/mosquitto:v1.0.0
    ports:
      - 1883:1883
      - 9001:9001
    deploy:
      mode: replicated
      replicas: 1
  zigbee2mqtt:
    image: rqure/zigbee2mqtt:v1.0.0
    volumes:
      - /run/udev:/run/udev:ro
      - /dev/ttyUSB0:/dev/ttyACM0
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
  qmq2mqtt:
    image: rqure/qmq2mqtt:v1.0.3
    environment:
      - QMQ_LOG_LEVEL=0
    deploy:
      mode: replicated
      replicas: 1
  garage:
    image: rqure/garage:v1.0.21
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 20000:20000
networks:
  default:
    attachable: true
