version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - "constraint:node==qserver"
  clock:
    image: rqure/clock:v2.0.10
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
  exchange:
    image: rqure/exchange:v2.0.2
    deploy:
      mode: replicated
      replicas: 1
    hostname: '{{.Node.Hostname}}'
networks:
  default:
    attachable: true
